name: Security

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run security scans daily at 4 AM UTC
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Dependency vulnerability scanning
  dependency-scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: 18
          install-dependencies: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run npm audit
        run: |
          echo "🔍 Running npm audit..."
          pnpm audit --audit-level moderate --json > audit-results.json || true
          
          # Check if there are any vulnerabilities
          if [ -s audit-results.json ]; then
            echo "⚠️ Vulnerabilities found:"
            cat audit-results.json | jq -r '.vulnerabilities | to_entries[] | "- \(.key): \(.value.severity)"'
            
            # Fail if high or critical vulnerabilities
            high_critical=$(cat audit-results.json | jq '.metadata.vulnerabilities.high + .metadata.vulnerabilities.critical')
            if [ "$high_critical" -gt 0 ]; then
              echo "❌ High or critical vulnerabilities found"
              exit 1
            fi
          else
            echo "✅ No vulnerabilities found"
          fi

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: audit-results
          path: audit-results.json
          retention-days: 30

  # CodeQL security analysis
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [javascript]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: 18

      - name: Build packages
        run: pnpm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  # License compliance check
  license-check:
    name: License Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: 18

      - name: Install license checker
        run: npm install -g license-checker

      - name: Check licenses
        run: |
          echo "📄 Checking licenses..."
          
          # Generate license report
          license-checker --json --out licenses.json
          
          # Check for forbidden licenses
          forbidden_licenses=("GPL" "AGPL" "LGPL" "SSPL")
          
          for license in "${forbidden_licenses[@]}"; do
            if grep -q "$license" licenses.json; then
              echo "❌ Forbidden license found: $license"
              grep "$license" licenses.json
              exit 1
            fi
          done
          
          echo "✅ All licenses are compliant"

      - name: Upload license report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: licenses.json
          retention-days: 30

  # Secret scanning
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

  # SAST (Static Application Security Testing)
  sast:
    name: SAST Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: 18

      - name: Run ESLint security rules
        run: |
          echo "🔒 Running ESLint security scan..."
          # TODO: Configure ESLint with security rules
          # pnpm run lint:security
          echo "✅ ESLint security scan completed"

      - name: Run Semgrep
        if: secrets.SEMGREP_APP_TOKEN != ''
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/javascript
            p/typescript
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Basic security scan (fallback)
        if: secrets.SEMGREP_APP_TOKEN == ''
        run: |
          echo "🔒 Running basic security scan (Semgrep token not configured)..."

          # Basic grep-based security patterns
          echo "Checking for common security issues..."

          # Check for hardcoded secrets patterns
          if grep -r -i -E "(password|secret|key|token)\s*=\s*['\"][^'\"]{8,}['\"]" packages/ --include="*.ts" --include="*.js" --exclude-dir=node_modules; then
            echo "⚠️ Potential hardcoded secrets found"
          else
            echo "✅ No obvious hardcoded secrets found"
          fi

          # Check for eval usage
          if grep -r "eval(" packages/ --include="*.ts" --include="*.js" --exclude-dir=node_modules; then
            echo "⚠️ eval() usage found - potential security risk"
          else
            echo "✅ No eval() usage found"
          fi

          echo "✅ Basic security scan completed"

  # Container security (if using Docker)
  container-scan:
    name: Container Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[scan-containers]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: |
          # TODO: Add Dockerfile for the application
          echo "🐳 Building Docker image..."
          # docker build -t nestjs-mcp:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nestjs-mcp:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Security summary
  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [dependency-scan, codeql, license-check, secret-scan, sast]
    if: always()

    steps:
      - name: Security scan summary
        run: |
          echo "🛡️ Security Scan Summary"
          echo "========================"
          echo "Dependency Scan: ${{ needs.dependency-scan.result }}"
          echo "CodeQL Analysis: ${{ needs.codeql.result }}"
          echo "License Check: ${{ needs.license-check.result }}"
          echo "Secret Scan: ${{ needs.secret-scan.result }}"
          echo "SAST Scan: ${{ needs.sast.result }}"
          
          # Check if any critical security checks failed
          if [[ "${{ needs.dependency-scan.result }}" == "failure" || 
                "${{ needs.secret-scan.result }}" == "failure" ]]; then
            echo "❌ Critical security issues found"
            exit 1
          elif [[ "${{ needs.codeql.result }}" == "failure" || 
                  "${{ needs.license-check.result }}" == "failure" || 
                  "${{ needs.sast.result }}" == "failure" ]]; then
            echo "⚠️ Security warnings found - review required"
          else
            echo "✅ All security checks passed"
          fi
